version: '3'

services:
    mongo:
        image: mongo:4
        container_name: some-mongo
        ports:
        - 27018:27017

    redis:
        image: redis
        container_name: some-redis
        ports:
        - 6379:6379
    
    orientdb:
        image: orientdb:2.2
        container_name: some-orientdb
        ports:
        - 2480:2480